### ISSUE TITLE
Tabbing issue #2

### ISSUE THREAD

**Issue by xplustwo** [tholman/elevator.js#9] opened 2015-04-22 03:04 UTC
If you click "scroll to top" but then tab out while the music is playing, the music will keep playing despite the page having reached the top. Then when you switch back to the page, it will abruptly stop with a "ding", but youll still be at the bottom (of the page).

**Comment by tholman** [comment] 2015-04-22 03:48
Duplicate of #2

**Closed by tholman** 2015-04-22 03:48 UTC
